---
kind: Service
apiVersion: v1
metadata:
  name: digital-webadmin
  namespace: default
spec:
  ports:
    - name: service-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    run: digital-webadmin
